config/routes.rb
Rails.application.routes.draw do

  resources :charges

  
  get 'thanks' => 'thanks#index'
  get 'get_started' => 'get_started#index'
  get 'testimonial' => 'testimonial#index'
  get 'contact' => 'contact#index'
  get 'faq' => 'faq#index'
  get 'about' => 'about#index'
  get 'home' => 'home#index'
  root 'home#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end 

  def create
    binding.pry
    @amount = case params[:plan_chosen]
      when "0" then 4900 
      when "1" then 9900
      when "2" then 19900
      else
        raise 'Plan not supported'
      end

    @description = case params[:plan_chosen]
      when "0" then 'Tour Foundations 1'
      when "1" then 'Tour Foundations 2'
      when "2" then 'The Cul-De-Sac'
      else
        raise 'Plan not supported'
      end       
    begin  
      customer = Stripe::Customer.create(
        :email => params[:stripeEmail],
        :source  => params[:stripeToken]
      )
  
      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => @amount,
        :description => @description,
        :currency    => 'usd'
      ) 
  
      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_charge_path
      end
      redirect_to thanks_path
    end 
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/get_started_controller.rb
class GetStartedController < ApplicationController

  def index
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/testimonial_controller.rb
class TestimonialController < ApplicationController
  def index
  end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController

  def index
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/get_started_helper.rb
module GetStartedHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/testimonial_helper.rb
module TestimonialHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/about/index.html.erb
  <div id="getstarted">
    <div class="5grid-layout" id="content">
      <div class="row">
        <div class="12u">    
          <section>
            <div class="post">
              <h2>About <%= image_tag("van.png", class: "van-icon") %></h2>
              <p>Bandturo is an affordable tour booking service for artists at any level. It is based on a process developed over a decade of 
        independent touring experience. We believe that all artists should be able to make a living from their craft, and we launched Bandturo to help 
        empower artists to do it. <br><br>
        We help you from start to finish to help make sure you have access to the know-how to succeed in your own way. We only charge 
        a one-time fee to set-up your one-sheet, high impact press kit, email tree, and route skeleton. All of these are free to take with you and use in the future, 
        even if you decide to not continue booking through us. Everything you make at the show is for you to keep. We take no commission and do not charge 
        additional fees. We want you to make money doing what you love. Once set-up and booking is complete, you are free to reap all the benefits of your 
        hard work and creativity. Our goal is to make a massive impact on the amount of music that is put into this world during our lives by creating more professional artists making a living off of music. If
        this sounds good to you then sign up today so the process can get started.</p>
              <p>&nbsp;</p>
                 <p class="button-style"><a href="getstarted.html">Get Started</a></p>
         <p><iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fbandturo&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="170" height="250" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe></p>      
      </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/charges/create.html.erb
<h2>Thanks, your payment was successfully submitted!</h2>

app/views/contact/index.html.erb
  <div id="getstarted">
    <div class="5grid-layout" id="content">
      <div class="row">
        <div class="12u">
          <section>
            <div class="post">
              <h2>Contact <%= image_tag("van.png", class: "van-icon") %></h2>
              <p>Please feel free to contact us by phone or email any time. It's cool if you have a lot of questions.</p>
              <p>&nbsp;</p>
              <p><h2>(352)354-7461</h2></p>
              <p><h2>booking@bandturo.com</h2></p>
              <p>&nbsp;</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/faq/index.html.erb
  <div id="faq">
    <div class="5grid-layout" id="content">
      <div class="row">
        <div class="12u">
          <section>
            <div class="post">
              <h2>Frequently Asked Questions <%= image_tag("van.png", class: "van-icon") %></h2>
              <br />
              <br />
              <br />
              <h2>I gave you my money--what happens now?</h2><br>
              <p>As soon as we receive your payment we will contact you to go over the things we need from you to start the tour booking process. Some things we will be looking for are any photos, links, press coverage, etc. that you think will be useful in getting you booked across the country. At this first contact, we will also answer any more questions you may have.</p>
              <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>

              <h2>Our bass player messed up big time and got married. Can I postpone?</h2><br>
              <p>Yes. There is no obligation to use our work for anything and you are not penalized if you miss a gig or have to cancel.</p>
              <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>

              <h2>Do you guarantee we will get rich or what?</h2><br>
              <p>Do we guarantee we will get you paid? Hell no. At least not yet. (We are working on it though...) If this is your first time, it is super likely
              that you will end up losing money in exchange for the learning and spiritual experience. That's why we offer our services at such a low price.
              We know the price we have to pay as serious artists. Keep at it, and it will get better with time. 
              Our friend Bo actually made money on his band's first tour. He wrote our <a href="testimonial.html">testimonial.</a></p>
              <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
              
              <h2>What if I am a solo artist?</h2><br>
              <p>No problem. We can get you booked.</p>      
              <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>
              
              <h2>Do you only book for certain genres?</h2><br>
              <p>We book for all genres. Yeah, some are more difficult to book. We also think genres are kind of stupid and outplayed.       </p>      
              <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>   
              
              <h2>I don't think we're ready. When should we start?</h2><br>
              <p>We highly recommend starting the process today. Although it is not completely necessary, the rule of thumb is to start booking your tour at least three months out. Six months is best. Therefore it's a good idea to get your marketing materials, dates, and a rough tour route 
              ready now. It can always be updated later, and 100% of tours that don't happen don't happen because of preparation.<br><br>Don't worry about money--you will find it. 
              And don't let other people hold you down. If you are ready then don't worry about who will be ready when it's time to leave. They should be worried about that, not you.</p>      
              <p>&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>  
       
              <strong>Heard enough?</strong>
              <p class="button-style"><a href="getstarted.html">I'm ready. Let's go.</a></p>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/get_started/index.html.erb
<h1>working</h1>
<h2>working</h2>
<div id="getstarted">
  <div class="5grid-layout" id="content">
    <div class="row">
      <div class="12u">
        <section>
          <div class="post">     
            <h2 id="get-started-header">Get Started&nbsp;&nbsp; <%= image_tag("van.png", class: "van-icon") %></h2><br>
            <h3 id="get-started-subtext-1" align="center">$49</h3>
            <p id="get-started-subtext-2" align="center">Limited-time, introductory offer</p>
            <br />
          </div>
          <p>
            <a href="https://bandturo.com" target="_blank">
              <%= image_tag("road.png", alt: "Bandturo - Touring Artist Dream Machine", class: "van-on-road-img") %>
            </a>
          </p>
          <p>&nbsp;</p> 
          <h2>The best gigs are booked six months ahead of time</h2>
          <p>&nbsp;</p>
          <p>Six months is best. Three months is fine. Tomorrow? We will help with that. What is important right now 
          is that you get the ball rolling. Use our secure 
          payment system and we will get to work for you immediately. The set-up process typically takes about a 
          week to complete. After set-up, we will begin contacting our network of about 2,000 talent buyersyourbehalf. 
          You keep all the money from the door, merch, etc. We keep a constant stream of communication oandavailable. 
          We also offer other services behind the scenes if needed--we've been there. Let us know how we can hyoube successful.</p>
          <p>&nbsp;</p>  
        </section>
  
        <section id="price-columns">
          <div class="columns">
            <ul class="price">
              <li class="header"><h1>Tour Foundations I</h1></li>
              <li class="product-price"><h1>$49</h1></li>
              <li class="product-perks">
                <h1>One Sheet | Press Kit | Tour Route</h1>
                <h1>(Unlimited) Email Blasts | Mentor</h1>
              </li>
              <li class="product-info">
                <p>Save hours of boring booking and get set up with a 
                clean looking system that will put you in contact with talent buyers 
                in any region of the country. Be your own agent. Close your own gig 
                deals. But without the tedious stuff.
                </p>
              </li>
              <li class="grey">
                <%= form_tag charges_path, :class => "pay-button" do %>
                  <article>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                  </article>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="Tour Foundations 1"
                          data-amount="4900"
                          data-locale="auto"
                          data-label="Get Started">
                  </script>
                  <input type="hidden" name="plan_chosen" value="0"/>
                <% end %>
                </form>
              </li>
            </ul>
          </div>
          <div class="columns">
            <ul class="price">
              <li class="header"><h1>Tour Foundations II</h1></li>
              <li class="product-price"><h1>$99</h1></li>
              <li class="product-perks">
                <h1>One Sheet | Press Kit | Tour Route</h1> 
                <h1>(Unlimited) Email Blasts | Booking Agent</h1> 
                <h1>Budget Analysis | Verified Open Mic Fill-ins</h1>
              </li>
              <li class="product-info">
                <p>As musicians ourselves, we understand that many shows 
                on the road can be duds--even with the best planning. We will build out everything, 
                have an experienced agent book all the paying gigs we can for you, and fill in 
                most/all of the other open dates with personally verified open mic nights. 
                More than half the time, 
                playing an open mic will sell you more merch and win over more new fans than 
                the low paying gigs often offered to new artists. Getting in front of more people 
                in that town now means playing for more fans next time, and helps leverage your 
                deal in that market next time you tour. You 
                get the most of your first few times on the road. More money now, and more money later.
                </p>
              </li>
              <li class="grey">
                <%= form_tag charges_path, :class => "pay-button" do %>
                  <article>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                  </article>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="Tour Foundations 2"
                          data-amount="9900"
                          data-locale="auto"
                          data-label="Get Started">
                  </script>
                  <input type="hidden" name="plan_chosen" value="1"/>
                <% end %>
                </form>
              </li>
            </ul> 
          </div>
          <div class="columns">
            <ul class="price">
              <li class="header"><h1>The Cul-de-sac</h1></li>
              <li class="product-price"><h1>$199</h1></li>
              <li class="product-perks">
                <h1>One Sheet | Press Kit</h1> 
                <h1>Booking Agent | 5-Market Development</h1>
              </li>
              <li class="product-info">
                <p>Not everyone can take off form work and family, and 
                go on the road for weeks at a time. We will look at your area and help 
                you find gigs that are driveable/busable on weekends. This helps keep travel 
                costs low while building a steady fanbase to use for extra income or launching 
                into a full-time career musician. Shower, and repeat.
                </p>
              </li>
              <li class="grey">
                <%= form_tag charges_path, :class => "pay-button" do %>
                  <article>
                    <% if flash[:error].present? %>
                      <div id="error_explanation">
                        <p><%= flash[:error] %></p>
                      </div>
                    <% end %>
                  </article>
                  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                          data-description="The Cul-de-sac"
                          data-amount="19990"
                          data-locale="auto"
                          data-label="Get Started">
                  </script>
                  <input type="hidden" name="plan_chosen" value="2"/>
                <% end %>
              </li>
            </ul>
          </div>
        </section>
      </div>
    </div>
  </div> 
</div>

app/views/home/index.html.erb
<div id="page">
      <div class="5grid-layout index-top-row">
        <div class="row">
          <div class="12u">
            <div id="banner">
              <div class="banner-border"><%= image_tag("van.png", alt: "Bandturo - Touring Artist Dream Machine", class: "van-img") %><br>
              </div>
            </div>
          </div>
        </div>

        <div class="5grid-layout">
          <div class="row">          
            <div class="6u mobileUI-main-content">
              <div id="content">              
                <section>       
                  <div class="post">
                    <h2>Easy tour booking</h2>
                    <p>Take the next step.</p>
                    <p>&nbsp; </p>
                    <ul>
                      <li>Only $49 (One sheet (<a href="http://consonantmusic.com/about/pricing/">example pricing</a>), press   kit,  hundreds   of emails, tour route (<a href="https://optimoroute.com/pricing/">example pricing  </a>), mentor booking agent, budget  analysis)</li>
                      <li>Low cost, unlimited gigs</li>
                      <li>Invented, owned, and operated by artists</li>
                      <li>No hidden costs, monthly fees, or extra commissions</li>
                      <li>Earn more per gig</li>
                      <li>Additional options: press reach-out for each city, tour poster design-print-mailing, simple and   easy merch        design   with tight-budget artists in mind</li>
                      <li>Guaranteed shows - concert halls, bars, lounges, coffee shops, open mics</li>
                    </ul>
                    <p class="button-style"><a href="getstarted.html">Learn more</a></p>
                    <div id="subtext">
                      <p><strong>Bandturo</strong> is the automatic tour booking system. Save <i>months</i> worth of booking and paper pushing time   with our super-stacked process and national industry network.</p>
                      <p>&nbsp;</p>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bandturo - Tour booking dream machine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Abel|Clicker+Script|Oswald:300,400|Pacifico|Petit+Formal+Script" rel="stylesheet">
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="description" content="Book a tour today with our affordable, proven system and get paid to travel.">
  <meta name="keywords" content="Band, tour, booking, agent, booking agents, gigs, get more gigs">
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon">
  <link rel="icon" href="favicon.ico" type="image/x-icon">
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  
    ga('create', 'UA-33713101-3', 'auto');
    ga('send', 'pageview');
  </script>
</head>
<body class="homepage">
  <div id="wrapper">
      <header id="header">
        <div class="5grid-layout 5grid">
          <div class="row">
            <div class="12u" id="logo">
              <!-- Logo -->
              <div id="mobileUI-site-titlebar" class="logo-header">
                <%= image_tag("img04.png", alt: "Open Menu Icon", class: "icon-menu", id: "mobileUI-site-nav-opener") %>
                <h1><a href="#" class="mobileUI-site-title">Bandturo</a></h1>
                <p>Tour booking dream machine</p>
              </div>
            </div>
          </div>
        </div>
        <div class="5grid-layout 5grid">
          <div class="row">
            <div class="12u" id="menu">
              <div id="menu-wrapper">
                <nav class="mobileUI-site-nav">
                  <div class="icon-close">
                    <%= image_tag("ic_clear.png", alt: "Close Menu Icon", class: "icon-close") %>
                  </div>
                  <ul>
                    <li><%= link_to "Home", '/home', :method => :get, :class => 'nav_link'%></li>
                    <li><%= link_to "About", '/about', :method => :get, :class => 'nav_link'%></li>
                    <li><%= link_to "FAQ", '/faq', :method => :get, :class => 'nav_link'%></li>
                    <li><%= link_to "Contact", '/contact', :method => :get, :class => 'nav_link'%></li>
                    <li><%= link_to "Testimonial", '/testimonial', :method => :get, :class => 'nav_link'%></li>
                    <li><%= link_to "Get Started", '/get_started', :method => :get, :class => 'nav_link get_started_link'%></li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </header>
    </div> 
  <%= yield %>
    <div class="5grid-layout 5grid">
      <div class="row" id="footer-content"></div>
    </div>
    <div id="copyright" class="5grid-layout 5grid">
      <section>
        <p>&copy; Bandturo | 726 NW 8th Ave Suite F, Gainesville, Florida 32601 | (352)354-7461</p>
      </section>
    </div>
  </div>
</body>
</html>

app/views/testimonial/index.html.erb
  <div id="getstarted">
    <div class="5grid-layout" id="content">
      <div class="row">
        <div class="12u">    
          <section>      
            <div class="post">
              <h2>What's it going to be like my first time? &nbsp; <%= image_tag("van.png", alt: "Bandturo - Touring Artist Dream Machine", class: "van-icon") %>
              <h1>We recently did a free workshop for local artists on how to go on tour.</h1> 
              <h1>To get an idea of what it's like to have a truly successful first run, we asked Bo Campbell from touring Florida band <i>In Motion</i>:</h1>
              <br /> 
              <h1>"So, steps to leave on tour... What are the things that really matter? And what are the things don't matteras much as they think?"</h1><br />
              <br />
              <a href="getstarted.html"><%= image_tag("bolarge.png", alt: "Bandturo - Touring Artist Dream Machine", class: "bo-img") %></a>
              <div id="subtext">
                <br />
                <p><strong>Bo</strong>: For me... personally being ready in all facets. Like, focused on what you're about to undertake. Not the performing, but the time away from home, the not knowing what may come, and being cool with that. Getting yourself excited for each opportunity that's about to come. Kind of "clear your mind" of everything, but knowing you're about to get go play  your music. Things that don't matter that much? Idk. Really, like, I tried my best to not worry about how the shows would go--bad or   good--because you never know what's going to happen at the venue or driving to it. So--jumping back--mental preparation is key to me. More  so then "do I have enough cables, strings blah blah blah." You can find those while you're out and about. I think it's more about what's important vs "there's not much that isn't." For a successful run, and a fun one. Money-wise you should already be prepared on all bases regardless of what venues say they'll pay. So, really, it comes back around to preparation. Before pulling out of the driveway. Mentally being focused on having a good time and taking it one show at a time. Not worrying about all of the bad things that can happen. If those things do happen, knowing it's not the end of the world and having a plan to adapt. High and calm spirits go a long way towards everything, and before you know it you're back home and just had a killer time. Don't worry about where you're going to sleep. You're in a vehicle--if it comes down to it--  that you can sleep in. Idk--I feel like I just told you a bunch and didn't give you anything to use. And I've only done it once.”
                </p>
                <p>&nbsp;</p>
              </div>
              <p class="button-style"><a href="getstarted.html">Get Started</a></p>
              <p>Want to book a tour yourself? <a href="http://www.ascap.com/playback/2012/12/wecreatemusic/booking-your-own-tour-a-how-to-guide.aspx" target="blank">Check out this article</a> on one artist's approach from the ASCAP website.</p>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/thanks/index.html.erb
<div class="thanks-text">
  <h1>Thank you!</h1>
  <br />
  <h2>Your payment was successfully submitted.</h2>
  <h3>A Bandturo representative will be contacting you shortly to get you going, so hang tight!</h3>
</div>